### ISSUE TITLE
Add information about how to create the dashboard in readme

### ISSUE THREAD

**Issue by johschmitz** [TenySmart/ModbusTCP2MQTT#13]
In the readme there is this gif:
https://github.com/TenySmart/ModbusTCP2MQTT/blob/main/images/diagram.gif
But no information on how to create it.
I successfully installed the add-on but am a bit puzzled now how to continue to see the data?

**Comment by ttvt** [comment]
Home assistant already support energy diagram. You can also use customize card like this:
[https://github.com/JonahKr/power-distribution-card](url).
