### ISSUE TITLE
TypeError: fromRegisters() got an unexpected keyword argument 'endian'

### ISSUE THREAD

**Issue by RV1989** [TenySmart/ModbusTCP2MQTT#14]
I'm getting the following error.
`  File "/ModbusTCP.py", line 260, in load_sma_register
    message = BinaryPayloadDecoder.fromRegisters(received.registers, endian=Endian.Big)`

and reading the pymodbus docs there is no mention for endian=
`classmethodfromRegisters(registers, byteorder='<', wordorder='>')`

**Comment by ttvt** [comment]
What's your model?
