### ISSUE TITLE
Sensors Available Through Add-on

### ISSUE THREAD

**Issue by lohita** [TenySmart/ModbusTCP2MQTT#28]
Hi, thanks for creating this great integration - I'm still getting the hang of it. I've only gotten the following sensors which were created when I installed this addon:
<img width="350" alt="image" src="https://user-images.githubusercontent.com/19561472/156873882-2c6a2732-5750-49b2-965b-26a5bb3ecf04.png">

How do I add ones for energy exported, energy imported from the grid, and energy consumed?

**Comment by ttvt** [comment]
For energy import/export, you will need a meter

**Comment by JMEAthletics** [comment]
Since the most recent update, I've lost the inverter's internal temperature, was this intentional? I was hoping for use of the inverters internal supply voltage and frequency logs too, i don't suppose these will be added at any point?

**Comment by ttvt** [comment]
You will have the temperature and voltage sensor if set scan_level to STANDARD or DETAIL.  However you will need to create frequency sensor manually from mqtt data
