### ISSUE TITLE
WARNING  MQTT: Server Error; Server not configured MQTT: Server Error; Server not configured

### ISSUE THREAD

**Issue by alexandretarnos** [TenySmart/ModbusTCP2MQTT#50]
Addon from Home assistant is showing this fail

**Comment by Destroyer81** [comment]
Hi have the same issue, any ideas?

**Comment by alexandretarnos** [comment]
Gi guys... I'm ok now, the addon os note working well using the option automatic in inverter-model. I Just defined my model and Bang..I Hope Works well for you too
![image](https://user-images.githubusercontent.com/67341823/193446722-1603dd8f-c820-440a-be1a-e9c9cdc77467.png)
