### ISSUE TITLE
Can and if so how to use with 2 Sungrow inverters

### ISSUE THREAD

**Issue by packy2000** [TenySmart/ModbusTCP2MQTT#7]
Hi!

I'm new to home assistant but this appears to only support one inverter, is that right ?  Thanks to others I found the correct MQQT config and details for home assistant configuration.yaml and that is all working but just for one inverter.

I have a SG5K-D and a SH5K-30.

Thanks!

**Comment by antonyclarage** [comment]
I have the same question, got multiple inverters (all SGxK-D...)

**Comment by ttvt** [comment]
Sorry, the multi inverters not support. I will add this feature sometime.
