### ISSUE TITLE
Unable to add Repositiory to Homeassistant

### ISSUE THREAD

**Issue by ptC7H12** [TenySmart/ModbusTCP2MQTT#8]
When trying to add the repo to HA an error will be thrown.
I try to Add: https://github.com/TenySmart/HassioAddon

Following error appears in the log:
![image](https://user-images.githubusercontent.com/4460900/141656656-573dceca-bebd-4320-a118-6c445b7cd775.png)

**Comment by ptC7H12** [comment]
Is it normal that the link in the log is different then from the original?
I typed: https://github.com/TenySmart/HassioAddon
In the log: https://github.com/TenySmart/HassioAddonsAddons

**Comment by ttvt** [comment]
I made a merge on it. Thankyou
